### ISSUE TITLE
Bug in find_source_in_db function

### ISSUE THREAD

**Issue by Exu-112** [astrodbtoolkit/astrodb_utils#49]
running the function returns this error:

```
Traceback (most recent call last):
  File "/SIMPLE-db/scripts/ingests/ultracool_sheet/Ingest_radial_velocities.py", line 44, in <module>
    match = find_source_in_db(
  File "/opt/anaconda3/envs/simple-db/lib/python3.10/site-packages/astrodb_utils/utils.py", line 185, in find_source_in_db
    db_name_matches = db.query_region(
  File "/opt/anaconda3/envs/simple-db/lib/python3.10/site-packages/astrodbkit2/astrodb.py", line 687, in query_region
    df[["ra", "dec"]] = df[[ra_col, dec_col]].apply(pd.to_numeric)  # convert everything to floats
  File "/opt/anaconda3/envs/simple-db/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/opt/anaconda3/envs/simple-db/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/opt/anaconda3/envs/simple-db/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['ra_deg', 'dec_deg'], dtype='object')] are in the [columns]"
```

The function expects the column names in db to be ra_deg and dec_deg but in SIMPLE they are ra and dec.

**Comment by kelle** [comment]
I think this function needs to take the ra and dec column names as inputs.
